# .github/workflows/email-step.yml
name: Test Email Step

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f2000757@ds.study.iitm.ac.in
        run: echo "Hello, world from GitHub Actions!"
